baseURL = "http://example.org/"
languageCode = "en-us"
title = "Mouui"
theme = "chunky"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "tag"
    name = "Tags"
    url = "/tags"
    weight = 0    
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 0    

[taxonomies]
    category = "categories"
    tag = "tags"
